apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: log-volume
  name: log-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
