volumes:
  mysql_data:
  log_volume:

networks:
  backend:

services:
  payment_gateway:
    depends_on:
      - db
      - bank_simulator
    build: ./payment_gateway
    image: shvalery/payment_gateway
    volumes:
      - log_volume:/var/log
    ports:
      - "8080:8080"
    networks:
      - backend

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: payment_gateway
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - backend

  bank_simulator:
    build: ./bank_simulator
    image: shvalery/bank_simulator
    volumes:
      - log_volume:/var/log
    networks:
      - backend
    expose:
      - "8081"