basePath: /api/v1/
definitions:
  transport.PaymentRequest:
    properties:
      amount:
        type: integer
      card:
        properties:
          cvv:
            type: string
          expiry_month:
            type: string
          expiry_year:
            type: string
          holder_name:
            type: string
          number:
            type: string
        type: object
      currency:
        type: string
    type: object
  transport.PaymentResponse:
    properties:
      code:
        type: string
      id:
        type: string
      maskedCardNumber:
        type: string
      status:
        type: string
      trackingID:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Valery
    url: http://linkedin.com/in/valeryshapetin/
  description: HTTP API for payment gateway
  title: Payment Gateway
  version: "1.0"
paths:
  /payment:
    post:
      consumes:
      - application/json
      description: Create Payment
      parameters:
      - description: Payment Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/transport.PaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.PaymentResponse'
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - BearerAuth: []
      tags:
      - payment
  /payment/{id}:
    get:
      consumes:
      - application/json
      description: Get Payment Status by id
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.PaymentResponse'
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get Payment Status
      tags:
      - payment
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
